In [37]:
#Exercise1
import scipy
from scipy.cluster.vq import kmeans,vq,whiten
# Score of 20 students in on subjects
student_scores = [[80] , [78] , [55] , [60] , [62] ,
                  [59] , [48] , [49] , [51] , [54] ,
                  [72] , [95] , [78] , [54] , [50] ,
                  [61] , [57] , [56] , [65] , [53]
                 ];

In [38]:
#Exercise2
student_scores = whiten(student_scores)
centroids,_ = kmeans(student_scores,2)

print(student_scores)
print(centroids)

[[6.53573177]
 [6.37233848]
 [4.49331559]
 [4.90179883]
 [5.06519213]
 [4.82010218]
 [3.92143906]
 [4.00313571]
 [4.16652901]
 [4.41161895]
 [5.8821586 ]
 [7.76118148]
 [6.37233848]
 [4.41161895]
 [4.08483236]
 [4.98349548]
 [4.65670889]
 [4.57501224]
 [5.31028207]
 [4.3299223 ]]
[[6.58474976]
 [4.54233358]]


In [39]:
#Exercise3
result,_ = vq(student_scores,centroids)

print(result)

[0 0 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1]


To compare the data with centroid and assign the observation to closet cluster.

In [40]:
#Exercise4
student_scores = whiten(student_scores)
centroids,_ = kmeans(student_scores,4)
result,_ = vq(student_scores, centroids)
print(student_scores)
print(centroids)
print(result,_)

[[6.53573177]
 [6.37233848]
 [4.49331559]
 [4.90179883]
 [5.06519213]
 [4.82010218]
 [3.92143906]
 [4.00313571]
 [4.16652901]
 [4.41161895]
 [5.8821586 ]
 [7.76118148]
 [6.37233848]
 [4.41161895]
 [4.08483236]
 [4.98349548]
 [4.65670889]
 [4.57501224]
 [5.31028207]
 [4.3299223 ]]
[[7.76118148]
 [6.29064183]
 [4.90179883]
 [4.22780149]]
[1 1 3 2 2 2 3 3 3 3 1 0 1 3 3 2 2 2 2 3] [2.45089942e-01 8.16966472e-02 2.65514103e-01 8.88178420e-16
 1.63393294e-01 8.16966472e-02 3.06362427e-01 2.24665780e-01
 6.12724854e-02 1.83817456e-01 4.08483236e-01 0.00000000e+00
 8.16966472e-02 1.83817456e-01 1.42969133e-01 8.16966472e-02
 2.45089942e-01 3.26786589e-01 4.08483236e-01 1.02120809e-01]


In [42]:
#Exercise5
student_scores = [[80 , 72] , [78 , 56] , [55 , 64] , [60 , 61] , [62 , 45] ,
                  [59 , 71] , [48 , 85] , [49 , 45] , [51 , 55] , [54 , 62] ,
                  [72 , 81] , [95 , 81] , [78 , 92] , [54 , 80] , [50 , 50] ,
                  [61 , 65] , [57 , 62] , [56 , 55] , [65 , 63] , [53 , 72]
                 ];
student_scores = whiten(student_scores)
centroids,_ = kmeans(student_scores,4)
result,_ = vq(student_scores, centroids)
print(student_scores)
print(centroids)
print(result)

[[6.53573177 5.57942592]
 [6.37233848 4.33955349]
 [4.49331559 4.9594897 ]
 [4.90179883 4.72701362]
 [5.06519213 3.4871412 ]
 [4.82010218 5.50193389]
 [3.92143906 6.58682226]
 [4.00313571 3.4871412 ]
 [4.16652901 4.26206146]
 [4.41161895 4.80450565]
 [5.8821586  6.27685415]
 [7.76118148 6.27685415]
 [6.37233848 7.12926645]
 [4.41161895 6.19936213]
 [4.08483236 3.87460133]
 [4.98349548 5.03698173]
 [4.65670889 4.80450565]
 [4.57501224 4.26206146]
 [5.31028207 4.88199768]
 [4.3299223  5.57942592]]
[[4.22099344 6.1218701 ]
 [4.37894029 3.87460133]
 [6.58474976 5.92039083]
 [4.79676028 4.9594897 ]]
[2 2 3 3 1 3 0 1 1 3 2 2 2 0 1 3 3 1 3 0]


The data is sepearate into 4 groups of kmean and and assign the observation to closet cluster.

In [20]:
#Exercise6
import scipy.constants
print("The PI is %1.6f"%scipy.constants.pi)
print("The speed is light is c = %.1f"%scipy.constants.c)
print("The newton's gravity constant is G = %.1F"%scipy.constants.g)


The PI is 3.141593
The speed is light is c = 299792458.0
The newton's gravity constant is G = 9.8


In [43]:
#Exercise7
scipy.constants.find("gram") 

['atomic mass unit-kilogram relationship',
 'electron volt-kilogram relationship',
 'hartree-kilogram relationship',
 'hertz-kilogram relationship',
 'inverse meter-kilogram relationship',
 'joule-kilogram relationship',
 'kelvin-kilogram relationship',
 'kilogram-atomic mass unit relationship',
 'kilogram-electron volt relationship',
 'kilogram-hartree relationship',
 'kilogram-hertz relationship',
 'kilogram-inverse meter relationship',
 'kilogram-joule relationship',
 'kilogram-kelvin relationship']

 .find is to finds the first occurrence of the specified value.

In [23]:
#Exercise8
print(scipy.constants.physical_constants ["atomic mass unit-kilogram relationship"])

(1.6605390666e-27, 'kg', 5e-37)


In [46]:
#Exercise9
import scipy.constants
m = 45
c = scipy.constants.c
energy = m*(c**2)
print(energy)

4.044398304315679e+18


In [29]:
#Exercise10
import scipy.stats
import numpy as np
x = np.array([19 ,18 ,21 ,16 ,15 ,17 ,20 ,18]);
print(scipy.stats.tmin(x), scipy.stats.tmax(x), scipy.stats.tmean (x), scipy.stats.tvar(x));

15 21 18.0 4.0


In [32]:
#Exercise11
print(scipy.stats.describe(x));


DescribeResult(nobs=8, minmax=(15, 21), mean=18.0, variance=4.0, skewness=0.0, kurtosis=-1.0)


In [34]:
#Exercise12
import scipy.stats
import numpy as np
student_scores = [[80] , [78] , [55] , [60] , [62] ,
                  [59] , [48] , [49] , [51] , [54] ,
                  [72] , [95] , [78] , [54] , [50] ,
                  [61] , [57] , [56] , [65] , [53]
                 ];
print (scipy.stats.tmean(student_scores))
print (scipy.stats.tstd(student_scores))
print ((62 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))


61.85
[12.55838994]
[0.01194421]


- find trim mean of the array.
- find trim standard deviation of the array.
- to calculate the z-score

In [36]:
#Exercise13
import scipy.stats
import numpy as np
student_scores = [[80] , [78] , [55] , [60] , [62] ,
                  [59] , [48] , [49] , [51] , [54] ,
                  [72] , [95] , [78] , [54] , [50] ,
                  [61] , [57] , [56] , [65] , [53]
                 ];
print (scipy.stats.tmean(student_scores))
print (scipy.stats.tstd(student_scores))
print ((80 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((78 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((55 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((60 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((62 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((59 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((48 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((49 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((51 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((54 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((72 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((95 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((78 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((54 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((50 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((61 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((57 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((56 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((65 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))
print ((53 - scipy.stats.tmean(student_scores))/scipy.stats.tstd(student_scores))


61.85
[12.55838994]
[1.44524896]
[1.28599288]
[-0.54545209]
[-0.14731188]
[0.01194421]
[-0.22693992]
[-1.10284838]
[-1.02322034]
[-0.86396425]
[-0.62508013]
[0.80822462]
[2.63966959]
[1.28599288]
[-0.62508013]
[-0.9435923]
[-0.06768384]
[-0.386196]
[-0.46582404]
[0.25082833]
[-0.70470817]
